project_id: '645058'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
languages_mapping: &languages_mapping
  two_letters_code:
    pt-BR: pt-BR
files:
  - source: /i18n/pt/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
    languages_mapping: *languages_mapping
  - source: /docs/**/*.json
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    languages_mapping: *languages_mapping
  - source: /docs/**/*.mdx
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    languages_mapping: *languages_mapping
#  - source: /static/**/*.webp
#    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
#    languages_mapping: *languages_mapping

#  - source: /community/**/*
#    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-community/current/**/%original_file_name%
#    languages_mapping: *languages_mapping
#  - source: /versioned_docs/**/*
#    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%
#    languages_mapping: *languages_mapping
#
#  - source: /blog/**/*
#    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
#    languages_mapping: *languages_mapping
#
#  - source: /src/pages/**/*
#    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-pages/**/%original_file_name%
#    ignore: [/**/*.js, /**/*.jsx, /**/*.ts, /**/*.tsx, /**/*.css]
#    languages_mapping: *languages_mapping